#!/usr/bin/env bash
#
# Generate the RS256 keypair used to sign JWTs.
#
# Local and test only. In staging and production the keypair is generated by
# and stored in AWS Secrets Manager, injected as SECURITY__JWT_PRIVATE_KEY, and
# rotated on a schedule — a private key that has ever touched a developer's
# disk is not one you want signing production sessions.
#
# 2048-bit RSA: the floor for RS256, and adequate for a token that lives 15
# minutes. 4096 would double verification cost on every single authenticated
# request for no meaningful gain at this TTL.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

generate() {
    local dir="$1" label="$2"
    mkdir -p "$dir"

    if [[ -f "$dir/jwt_private.pem" ]]; then
        echo "  ${label}: already present, skipping"
        return
    fi

    openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
        -out "$dir/jwt_private.pem" 2>/dev/null
    openssl rsa -pubout -in "$dir/jwt_private.pem" \
        -out "$dir/jwt_public.pem" 2>/dev/null

    # Owner-read-only. The private key is a credential; a world-readable one on
    # a shared machine is a compromised credential.
    chmod 600 "$dir/jwt_private.pem"
    chmod 644 "$dir/jwt_public.pem"

    echo "  ${label}: generated"
}

echo "Generating JWT keypairs"
generate "$ROOT/secrets" "local dev"
generate "$ROOT/tests/fixtures/keys" "test"

# pytest-env in pyproject.toml points the test suite at this exact filename.
if [[ ! -f "$ROOT/tests/fixtures/keys/test_jwt_private.pem" ]]; then
    cp "$ROOT/tests/fixtures/keys/jwt_private.pem" \
       "$ROOT/tests/fixtures/keys/test_jwt_private.pem"
    cp "$ROOT/tests/fixtures/keys/jwt_public.pem" \
       "$ROOT/tests/fixtures/keys/test_jwt_public.pem"
fi

echo
echo "Done. secrets/ and tests/fixtures/keys/ are git-ignored."
