"""AI: review insights, image annotations, itineraries, assistant, usage.

Every table here holds **derived** data. Each one can be truncated and
regenerated, and nothing outside this module reads them as a source of truth —
which is what makes a model change, a prompt rewrite, or a bad batch a DELETE
rather than a migration with a backfill.

Written by hand rather than autogenerated. The autogenerated version wanted to
drop ``ck_rating_summaries_count_non_negative`` and its sibling — constraints
added in 0007 with a `CHECK` that the models do not declare — along with a
scattering of indexes that exist under different names. Applying it would have
silently removed the guard that stops a property's review count going negative.

Revision ID: 0009_ai
Revises: 0008_vendor_link
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0009_ai"
down_revision = "0008_vendor_link"
branch_labels = None
depends_on = None

_UUID = postgresql.UUID(as_uuid=True)
_TS = sa.DateTime(timezone=True)


def upgrade() -> None:
    # ── review insights ───────────────────────────────────────────────────
    op.create_table(
        "review_insights",
        sa.Column("id", _UUID, primary_key=True),
        sa.Column("review_id", _UUID, nullable=False),
        sa.Column("property_id", _UUID, nullable=False),
        sa.Column("sentiment", sa.String(10), nullable=False),
        sa.Column("summary", sa.Text, nullable=False),
        sa.Column(
            "aspects",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "positive_aspects",
            postgresql.ARRAY(sa.String(20)),
            nullable=False,
            server_default=sa.text("'{}'::varchar[]"),
        ),
        sa.Column(
            "negative_aspects",
            postgresql.ARRAY(sa.String(20)),
            nullable=False,
            server_default=sa.text("'{}'::varchar[]"),
        ),
        sa.Column("needs_attention", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("attention_reason", sa.String(200)),
        sa.Column("acknowledged_at", _TS),
        sa.Column("model", sa.String(60), nullable=False),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("created_at", _TS, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", _TS, nullable=False, server_default=sa.func.now()),
        # CASCADE both ways. An analysis of a review that no longer exists is
        # not a record worth keeping, and leaving it would let a deleted
        # review's summary survive on a property page.
        sa.ForeignKeyConstraint(
            ["review_id"], ["reviews.id"], ondelete="CASCADE", name="fk_review_insights_review"
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            ondelete="CASCADE",
            name="fk_review_insights_property",
        ),
        # One per review, which is what makes the writer an idempotent upsert
        # rather than a check-then-insert that loses its race.
        sa.UniqueConstraint("review_id", name="uq_review_insights_review"),
        sa.CheckConstraint(
            "sentiment IN ('positive','mixed','negative')", name="ck_review_insights_sentiment"
        ),
        # A reason is what someone reads months later when asked why a review
        # was escalated. Enforced here as well as in the domain.
        sa.CheckConstraint(
            "NOT needs_attention OR attention_reason IS NOT NULL",
            name="ck_review_insights_attention_reason",
        ),
    )
    op.create_index("ix_review_insights_property", "review_insights", ["property_id"])
    op.create_index(
        "ix_review_insights_attention",
        "review_insights",
        ["created_at"],
        postgresql_where=sa.text("needs_attention AND acknowledged_at IS NULL"),
    )
    # GIN so "which properties are criticised for noise" is an index scan.
    op.create_index(
        "ix_review_insights_negative",
        "review_insights",
        ["negative_aspects"],
        postgresql_using="gin",
    )

    op.create_table(
        "property_sentiment",
        sa.Column("property_id", _UUID, primary_key=True),
        sa.Column("analysed_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("positive_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("mixed_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("negative_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column(
            "aspect_tallies",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("created_at", _TS, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", _TS, nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            ondelete="CASCADE",
            name="fk_property_sentiment_property",
        ),
        # The three buckets are mutually exclusive, so they must sum. A drift
        # here means the rebuild query is wrong, and the constraint is how you
        # find that out in a test rather than in a chart.
        sa.CheckConstraint(
            "analysed_count = positive_count + mixed_count + negative_count",
            name="ck_property_sentiment_sums",
        ),
    )

    # ── image annotations ─────────────────────────────────────────────────
    op.create_table(
        "image_annotations",
        sa.Column("id", _UUID, primary_key=True),
        sa.Column("image_id", _UUID, nullable=False),
        sa.Column("property_id", _UUID, nullable=False),
        sa.Column("alt_text", sa.String(250), nullable=False),
        sa.Column("tags", postgresql.JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column(
            "suggested_amenities",
            postgresql.ARRAY(sa.String(40)),
            nullable=False,
            server_default=sa.text("'{}'::varchar[]"),
        ),
        sa.Column("flagged", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("flag_reason", sa.String(200)),
        sa.Column("reviewed_at", _TS),
        sa.Column("model", sa.String(60), nullable=False),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("created_at", _TS, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", _TS, nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["property_images.id"],
            ondelete="CASCADE",
            name="fk_image_annotations_image",
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            ondelete="CASCADE",
            name="fk_image_annotations_property",
        ),
        sa.UniqueConstraint("image_id", name="uq_image_annotations_image"),
        # Alt text is the accessibility deliverable. An empty string on a
        # content image is worse than a mediocre sentence, so the column
        # refuses to hold one.
        sa.CheckConstraint("length(trim(alt_text)) > 0", name="ck_image_annotations_alt_text"),
    )
    op.create_index("ix_image_annotations_property", "image_annotations", ["property_id"])
    op.create_index(
        "ix_image_annotations_flagged",
        "image_annotations",
        ["created_at"],
        postgresql_where=sa.text("flagged AND reviewed_at IS NULL"),
    )

    # ── itineraries ───────────────────────────────────────────────────────
    op.create_table(
        "generated_itineraries",
        sa.Column("id", _UUID, primary_key=True),
        sa.Column("request_hash", sa.String(64), nullable=False),
        sa.Column("city", sa.String(120), nullable=False),
        sa.Column("days", sa.SmallInteger, nullable=False),
        sa.Column("summary", sa.Text, nullable=False),
        sa.Column("plan", postgresql.JSONB, nullable=False),
        sa.Column(
            "referenced_property_ids",
            postgresql.ARRAY(_UUID),
            nullable=False,
            server_default=sa.text("'{}'::uuid[]"),
        ),
        sa.Column("low_confidence", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("model", sa.String(60), nullable=False),
        sa.Column("hit_count", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("expires_at", _TS, nullable=False),
        sa.Column("created_at", _TS, nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", _TS, nullable=False, server_default=sa.func.now()),
        # The cache key. Keyed on what was asked, never on who asked — see the
        # model docstring for why that is load-bearing rather than an
        # optimisation.
        sa.UniqueConstraint("request_hash", name="uq_generated_itineraries_hash"),
        sa.CheckConstraint("days BETWEEN 1 AND 21", name="ck_generated_itineraries_days"),
    )
    op.create_index("ix_generated_itineraries_expiry", "generated_itineraries", ["expires_at"])
    # No FK on the array — a cached plan referencing a property that is later
    # hard-deleted should expire, not block the delete. GIN so that expiry is
    # an index scan.
    op.create_index(
        "ix_generated_itineraries_refs",
        "generated_itineraries",
        ["referenced_property_ids"],
        postgresql_using="gin",
    )

    # ── assistant ─────────────────────────────────────────────────────────
    op.create_table(
        "assistant_messages",
        sa.Column("id", _UUID, primary_key=True),
        sa.Column("conversation_id", _UUID, nullable=False),
        sa.Column("user_id", _UUID),
        sa.Column("role", sa.String(10), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column(
            "suggested_property_ids",
            postgresql.ARRAY(_UUID),
            nullable=False,
            server_default=sa.text("'{}'::uuid[]"),
        ),
        sa.Column("needs_human", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("created_at", _TS, nullable=False, server_default=sa.func.now()),
        # Nullable: the assistant works signed out. CASCADE so deleting an
        # account takes the transcripts with it — they are guest-authored free
        # text and some fraction of it is personal whatever the box asked for.
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE", name="fk_assistant_messages_user"
        ),
        sa.CheckConstraint("role IN ('guest','assistant')", name="ck_assistant_messages_role"),
    )
    op.create_index(
        "ix_assistant_messages_thread", "assistant_messages", ["conversation_id", "created_at"]
    )
    op.create_index("ix_assistant_messages_created", "assistant_messages", ["created_at"])

    # ── usage ─────────────────────────────────────────────────────────────
    op.create_table(
        "ai_usage",
        sa.Column("id", _UUID, primary_key=True),
        sa.Column("user_id", _UUID),
        sa.Column("feature", sa.String(30), nullable=False),
        sa.Column("model", sa.String(60), nullable=False),
        sa.Column("input_tokens", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("output_tokens", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("latency_ms", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("succeeded", sa.Boolean, nullable=False, server_default=sa.text("true")),
        sa.Column("created_at", _TS, nullable=False, server_default=sa.func.now()),
        # SET NULL, not CASCADE: a deleted account must not erase the record of
        # what was spent. The row keeps its cost and loses its subject.
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="SET NULL", name="fk_ai_usage_user"
        ),
    )
    op.create_index("ix_ai_usage_feature_time", "ai_usage", ["feature", "created_at"])
    op.create_index("ix_ai_usage_user_time", "ai_usage", ["user_id", "created_at"])


def downgrade() -> None:
    """Safe, unlike most downgrades in this project.

    Everything here is derived and regenerable: dropping these tables loses
    cached itineraries and computed sentiment, both of which rebuild from the
    reviews and properties that remain.
    """
    op.drop_table("ai_usage")
    op.drop_table("assistant_messages")
    op.drop_table("generated_itineraries")
    op.drop_table("image_annotations")
    op.drop_table("property_sentiment")
    op.drop_table("review_insights")
